language: python

# To automatically push to anaconda cloud tag a relase in the git repository
# git tag -a v0.2.3 -m 'Version with working conda installer'
# git push --tags


jobs:
  include:
    - name: "linux"
      os: linux
      language: python
      python: 3.7           # this works for Linux but is ignored on macOS or Windows
      env:
        - CC=gcc-5
        - CXX=g++-5
    - name: "osx"
      os: osx
      language: sh
      before_cache:
        - brew cleanup
      cache:
        directories:
          - $HOME/Library/Caches/Homebrew
          - /usr/local/Homebrew
      addons:
        homebrew:
          packages: python3
      env:
        - CC=clang
        - CXX=clang++


install:
  - pip install -r requirements.txt
  - python setup.py install

# command to run tests
script: ./travis_test.sh

